---
# tasks file for letsencrypt-cloudflare
#
- name: Distribution
  debug: msg="{{ ansible_distribution }}"

- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"

- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"

- name: install  epel
  package:
    name: [epel-release]
    state: latest

- name: install required packages for CentOS 8 or RockyLinux
  package:
    name: [certbot,python3-certbot-dns-cloudflare]
    state: latest
  when:  (ansible_distribution == "CentOS" or "RockyLinux") and
          ansible_distribution_major_version == "8"

- name: install required packages for Centos 7
  package:
    name: [certbot,python2-certbot-dns-cloudflare]
    state: latest
  when:  ansible_distribution == "CentOS"  and ansible_distribution_major_version == "7"



#certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d coreserver.lnxsystems.com -m jasonviloria@lnxsystems.com --agree-tos -n
- name: ensure /root/.secrets dir exists
  file:
    path: /root/.secrets
    owner: root
    group: root
    state: directory
    mode: '0700'

- name: Set dns_cloudflare_api_token
  template:
    src: cloudflare.ini.j2
    dest: /root/.secrets/cloudflare.ini
    owner: root
    group: root
    mode: 0600

- name: Deploy certbot_getcert.sh
  template:
    src: certbot_getcert.sh.j2
    dest: /usr/local/bin/certbot_getcert.sh
    owner: root
    group: root
    mode: 0700

- name: Run the certbot_getcert.sh script
  command: "/usr/local/bin/certbot_getcert.sh {{item}}"
  with_items: "{{ letsencrypt_domains }}"

