---
- name: Install OpenSSL
  package:
    name: openssl
    state: latest


- name: check if the certificate directory exists
  stat:
    path: "{{ certificate_directory }}"
  register: certificate_directory_stat
  tags:
    - copy_ssl

- name: check if local ssl dir exists
  local_action: stat path="{{role_path}}/files/{{inventory_hostname}}"
  register: certs_in_role_dir
  tags:
    - copy_ssl


- name: Deploy Certificates
  include: deploy_certificates.yml
  when: (not certificate_directory_stat.stat.exists) and certs_in_role_dir.stat.exists 

- name: Make Certificates
  include: make_certificates.yml
  when: (not certificate_directory_stat.stat.exists) and (not certs_in_role_dir.stat.exists)

 
- name: Remove generated files if 'cleanup_all'
  file:
    path: "{{ item.full_path }}"
    state: absent
  with_items:
    - { full_path: "{{ certificate_directory + '/' + csr_filename }}"}
    - { full_path: "{{ certificate_directory + '/' + crt_filename }}"}
    - { full_path: "{{ certificate_directory + '/' + key_filename }}"}
    - { full_path: "{{ certificate_directory + '/' + intermediate_filename }}"}
    - { full_path: "{{ certificate_directory + '/' + fullchain_filename }}"}
  when: cleanup_all

- name: Remove certificate directory if 'cleanup_all' and didnt previously exist
  file:
    path: "{{ certificate_directory }}"
    state: absent
  when: (cleanup_all) and (not certificate_directory_stat.stat.exists)
