---
# tasks file for letsencrypt-cloudflare
#

- name: install  epel
  dnf:
    name: [epel-release]
    state: latest

- name: install required packages
  dnf:
    name: [certbot,python3-certbot-dns-cloudflare]
    state: latest

#certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d coreserver.lnxsystems.com -m jasonviloria@lnxsystems.com --agree-tos -n
- name: ensure /root/.secrets dir exists
  file:
    path: /root/.secrets
    owner: root
    group: root
    state: directory
    mode: '0700'

- name: Set dns_cloudflare_api_token
  template:
    src: cloudflare.ini.j2
    dest: /root/.secrets/cloudflare.ini
    owner: root
    group: root
    mode: 0600

- name: Deploy certbot_getcert.sh
  template:
    src: certbot_getcert.sh.j2
    dest: /usr/local/bin/certbot_getcert.sh
    owner: root
    group: root
    mode: 0700

- name: Run the certbot_getcert.sh script
  ansible.builtin.shell:
    cmd: "/usr/local/bin/certbot_getcert.sh {{item}}"
  with_items: "{{ letsencrypt_domains }}"
